### ISSUE TITLE
How can use it on a windows machine?

### ISSUE THREAD

**Issue by aftabnaveed** [ReekenX/phpcheck-git#6]
How can use it on a windows machine?

**Comment by ReekenX** [comment]
Hi. Since it is `bash` and `git hook` you will need to make few things:

* Setup GIT on Windows. Probably you did that already. If not: https://git-scm.com/download/win
* Setup BASH on Windows. Google "bash for windows" - plenty of information.
* Lamp? Because you will need to have `php` executable.

Sorry for too generic solution, but since I don't have (and don't want to) setup Windows and try myself it, can only suggest that.

Feel free to contact again about this if after setting up you will end up with some issues. I might be able to help resolve any compatibility issues.
